export const API_ERROR = 'API_ERROR';
export const POP_API_MESSAGE = 'POP_API_MESSAGE';
export const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS';

export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';

export const SET_ACTIVE_POST = 'SET_ACTIVE_POST';
export const SET_SORT_MODE = 'SET_SORT_MODE';